### PR TITLE
Abv updates

### LINKED ISSUE #7: Add ABV to Beers, Session and User Profile
It's fun to know how boozy all the beers people drank were. The database models needs to be updated to that for each beer we store the ABV. I think this will require a few updates throughout the code base:

- Updates to the test csv files to include the ABV of the beers.
- Updates to the `Beer` model ins the `models/models.py` file to have an ABV field
- Updates to the `csv_load` in `dbhelper` and the session adding function. (Though that's a hot mess anyway...)

I think a cool thing also would be adding a display of average abv on a persons profile for the beers which they brought, and maybe an average abv on the sessions page as well.

### PR DESCRIPTION
**Pull request by brigidangelini**
#7
- updated test csv to include abv
- updated session view and db imports to include abv and average abv
  - copied how avg abv method is implemented in FCMember class but queried by session id vs user
- updated user view and profiles to include abv and average abv
  - copied how average score method in FCMember class is implemented to create average abv method

Screen Shot 2020-11-27 at 4 32 35 PM

### CODE REVIEW

**Comment by drc0308** [comment]
@brigidangelini can you also add around `users/profile.html:37` a little Average ABV thing similar to the score to display? but otherwise this looks great! :) Thanks!

**Comment by brigidangelini** [comment]
> @brigidangelini can you also add around `users/profile.html:37` a little Average ABV thing similar to the score to display? but otherwise this looks great! :) Thanks!

yes! added, edit - I'm a clown, it's fixed

**Comment by brigidangelini** [comment]
added average abv to session views
Screen Shot 2020-11-27 at 5 28 08 PM

**Review by drc0308 — APPROVED** [review]
:tada: Looks great! Thanks so much :smile:

**Pull request merged**
