### PR TITLE
[WIP] Fix black flakiness

### PR DESCRIPTION
**Pull request by scott-eddy**
Work to address #37

### CODE REVIEW

**Comment by scott-eddy** [comment]
@drc56 this is a little worse than I thought.  Anyone can just merge anything willie-nillie, even when Travis reports it's running.  Even when the person isn't you! Can you update the required status checks for the repo to merge, see [here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks)

**Comment by scott-eddy** [comment]
Also, black failures are clearly not being reported correctly.  See the passing commit, [022ceee](https://github.com/drc56/flight_club/pull/38/commits/022ceeebb23ca3e2a07e07feaf6433e2710af248) which should be failing but is not

**Comment by scott-eddy** [comment]
Looking at the build in question [here](https://travis-ci.com/github/drc56/flight_club/builds/208425533) we see that black is exiting non-zero but docker-compose is exiting zero.  We need docker-compose to have the same exit condition as the command run within the container

**Comment by scott-eddy** [comment]
Also, @drc56 to highlight that you should restrict who has the ability to merge PRs Imma just merge this.

**Comment by drc0308** [comment]
@scott-eddy I think I gave it so you, @brigidangelini and @oliviaecruz can merge stuff. So use your power wisely?

**Comment by drc0308** [comment]
but maybe now PRs require at least one reviewer, who knows if I know how to use github correctly.

**Pull request merged**
